# Generated by Django 2.0.3 on 2018-03-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choise', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dogbreeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breed_Type', models.CharField(max_length=100)),
                ('DogImage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lengths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='ActivityLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity_Level', to='selector.Levels'),
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='Coatlength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coat_length', to='selector.Lengths'),
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='Drools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drool', to='selector.Choises'),
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='GoodWithChildren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Good_With_Children', to='selector.Choises'),
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='GroomingDemand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grooming_Demand', to='selector.Levels'),
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='Intelligence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Intelligences', to='selector.Levels'),
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='SheddingLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shedding_Level', to='selector.Levels'),
        ),
        migrations.AddField(
            model_name='dogbreeds',
            name='Size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sizes', to='selector.Sizes'),
        ),
    ]
