# Generated by Django 2.0.2 on 2018-03-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogbreeds',
            old_name='ActivityLevel',
            new_name='Activity',
        ),
        migrations.RenameField(
            model_name='dogbreeds',
            old_name='GroomingDemand',
            new_name='Grooming',
        ),
        migrations.RenameField(
            model_name='dogbreeds',
            old_name='SheddingLevel',
            new_name='Shedding',
        ),
    ]
