# Generated by Django 2.0.2 on 2018-03-28 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0002_auto_20180328_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='choises',
            name='ChoiseDrool',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
