# Generated by Django 2.0.2 on 2018-05-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_answer', models.TextField()),
                ('game_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=50)),
                ('tournament_start_date', models.DateTimeField(verbose_name='start date')),
                ('tournament_end_date', models.DateTimeField(verbose_name='end date')),
                ('tournament_category', models.CharField(blank=True, max_length=100, null=True)),
                ('tournament_difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('tournament_question', models.TextField()),
                ('tournament_high_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.CharField(max_length=50)),
                ('user_phone', models.IntegerField(default=0)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Role')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User'),
        ),
    ]
