# Generated by Django 2.0.3 on 2018-06-02 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='start date'),
        ),
    ]
